### ISSUE TITLE
Runtime error in dynamic map

### ISSUE THREAD

**Issue by Ma29-HIT** [Zhefan-Xu/map_manager#15]
Hi Zhefan, thank you for releasing the code and I really appreciate your work. When I try to run dynamic map in uav_simulator with the gazebo world `/simple_box/simple_box_dynamic_3.world`, the process has died with exit code -6. The error info is as below:

```bash
/usr/include/eigen3/Eigen/src/Core/Product.h:95: 
Eigen::Product<Lhs, Rhs, Option>::Product(const Lhs&, const Rhs&) [with _Lhs = Eigen::Matrix<double, -1, -1>; 
_Rhs = Eigen::Matrix<double, -1, -1>; 
int Option = 0; Eigen::Product<Lhs, Rhs, Option>::Lhs = Eigen::Matrix<double, -1, -1>; 
Eigen::Product<Lhs, Rhs, Option>::Rhs = Eigen::Matrix<double, -1, -1>]: Assertion `lhs.cols() == rhs.rows() && "invalid matrix product" && "if you wanted a coeff-wise or a dot product use the respective explicit functions"' failed.
```

Then process has died with exit code -6.

My config files are:
dynamic map params:
```yaml
sensor_input_mode: 0 # 0 camera 1: lidar
localization_mode: 1 # 0: pose (default) 1: odom
depth_image_topic: /camera/depth/image_raw
# depth_image_topic: /no_topic
# pose_topic: /mavros/local_position/pose
# odom_topic: /mavros/local_position/odom

pose_topic: /CERLAB/quadcopter/pose
odom_topic: /CERLAB/quadcopter/odom

# robot size
robot_size: [0.5, 0.5, 0.3]

# Camera Parameters
depth_intrinsics: [554.254691191187, 554.254691191187, 320.5, 240.5] # fx,  fy, cx, cy
depth_scale_factor: 10 # 1000 for Intel Realsense Camera
depth_min_value: 0.5
depth_max_value: 5.0
depth_filter_margin: 2 # filter
depth_skip_pixel: 2 # filter
image_cols: 640
image_rows: 480
body_to_camera: [0.0,  0.0,  1.0,  0.09,
                -1.0,  0.0,  0.0,  0.0 ,   
                 0.0, -1.0,  0.0,  0.095,
                 0.0,  0.0,  0.0,  1.0]

# Raycasting
raycast_max_length: 5.0
p_hit: 0.70
p_miss: 0.35
p_min: 0.12
p_max: 0.97
p_occ: 0.80


# Map
map_resolution: 0.1
ground_height: -0.1 # m
map_size: [40, 40, 3] # meter. in x y z direction (reserved size)
local_update_range: [5, 5, 5]
local_bound_inflation: 3.0 # inflate local bound in meter
clean_local_map: false

# visualziation
local_map_size: [20, 20, 6] # meter. in x y z direction (only for visualization)
max_height_visualization: 2.5 # m
visualize_global_map: true
verbose: false

prebuilt_map_directory: "No"
# prebuilt_map_directory: "/home/cerlab/map/static_map.pcd"
```
onboard detector params:
```yaml
localization_mode: 0 # 0: pose (default) 1: odom

depth_image_topic: /camera/depth/image_raw
aligned_depth_image_topic: /camera/depth/image_raw
color_image_topic: /camera/color/image_raw
pose_topic: /CERLAB/quadcopter/pose
odom_topic: /CERLAB/quadcopter/odom

# depth_image_topic: /camera/depth/image_rect_raw
# aligned_depth_image_topic: /camera/aligned_depth_to_color/image_raw
# pose_topic: /mavros/local_position/pose
# odom_topic: /vins_estimator/imu_propagate

# Camera Parameters
# depth_intrinsics: [386.22674560546875, 386.22674560546875, 317.3930969238281, 239.78431701660156] # fx,  fy, cx, cy realsense
depth_intrinsics: [554.254691191187, 554.254691191187, 320.5, 240.5] # fx,  fy, cx, cy simulation
color_intrinsics: [554.254691191187, 554.254691191187, 320.5, 240.5] # fx,  fy, cx, cy simulation
#color_intrinsics: [608.08740234375, 608.08740234375, 317.48284912109375, 234.11557006835938] # intel realsense
# depth_scale_factor: 1000 # 1000 for Intel Realsense Camera
depth_scale_factor: 10 # simulation
depth_min_value: 0.5
depth_max_value: 5.0
depth_filter_margin: 10 # filter
depth_skip_pixel: 2  # filter
image_cols: 640
image_rows: 480
body_to_camera: [0.0,  0.0,  1.0,  0.09,
                -1.0,  0.0,  0.0,  0.0 ,   
                 0.0, -1.0,  0.0,  0.095,
                 0.0,  0.0,  0.0,  1.0]
body_to_camera_color: [0.0,  0.0,  1.0,  0.09,
                -1.0,  0.0,  0.0,  0.0 ,   
                 0.0, -1.0,  0.0,  0.095,
                 0.0,  0.0,  0.0,  1.0]



# Raycasting (max depth)
raycast_max_length: 5.0

# time difference
time_difference: 0.033

# sensor data processing
voxel_occupied_thresh: 5 # min num of points for a voxel to be occupied in voxel filter

# dbscan
ground_height: 0.1 # height of ground to remove ground points
dbscan_min_points_cluster: 20 # 20: 4.0m range; 30: 3.5m range 40: 3.0m range
dbscan_search_range_epsilon: 0.1 # searching range radius

# bounding box filtering
filtering_BBox_IOU_threshold: 0.05
yolo_overwrite_distance: 10

# tracking and data association
history_size: 100 # size of tracking history. history[0] is current detection
prediction_size: 20 # size of prediction
similarity_threshold: 0.02 # similiary threshold for data association matching comparison
retrack_similarity_threshold: 0.015  # similiary threshold for retracking
fix_size_history_threshold: 10 # History threshold (num of frames) to fix box size
fix_size_dimension_threshold: 0.4 # dimension threshold (size of proportional) to fix box size

e_p: 0.25
e_q_pos: 0.01
e_q_vel: 0.05
e_q_acc: 0.05
e_r_pos: 0.04
e_r_vel: 0.3
e_r_acc: 0.6

kalman_filter_averaging_frames: 10

# classification
frame_skip: 5 # num of frames skiped when comparing 2 point clouds
dynamic_velocity_threshold: 0.15
dynamic_voting_threshold: 0.8
maximum_skip_ratio: 0.5 # the upper limit of points that are skipped(out of previous FOV) to be classfified as dynamic
frames_force_dynamic: 10 # Range of searching dynamic obstacles in box history
frames_force_dynamic_check_range: 30 # threshold for forcing dynamic obstacles
dynamic_consistency_threshold: 5 # obstacles being voted as dynamic for continuous k frames are eligible to be classified as dynamic

# constrain size
constrain_size: false
target_object_size: [0.5, 0.5, 1.5]
```

I found that this error occurs often when the drone is close to the moving obstacle. Could you provide some advice?
